security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_home  # Redirection après déconnexion vers la page d'accueil

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Configuration des accès
    access_control:
        # Routes administrateur
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Routes nécessitant une connexion
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/trajet/new, roles: ROLE_USER }
        - { path: ^/trajet/\d+/edit, roles: ROLE_USER }
        - { path: ^/reservation, roles: ROLE_USER }
        - { path: ^/vehicule, roles: ROLE_USER }
        # Routes publiques
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/trajet$, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10